### ISSUE TITLE
There's no ks-jenkins image in dockerhub kubesphere project

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/ks-installer#1352]
![image](https://user-images.githubusercontent.com/18692628/112602378-8b43c600-8e4e-11eb-8d3b-a6717a3666c4.png)

There's no ks-jenkins image in dockerhub kubesphere project, but it's needed is at pulling_images.sh - kubesphere/ks-jenkins:2.249.1

/kind bug
/area devops

**Comment by LinuxSuRen** [comment]
Please check the document of [ks-jenkins](https://github.com/kubesphere/ks-jenkins#get-started).

`ks-jenkins:2.249.1` is not released yet. So I guess this is not a bug instead of a support request. But thanks for reporting this. I'd rather keep this issue open until we really have a `kubesphere/ks-jenkins:2.249.1`.

/kind support

**Comment by JohnNiang** [comment]
I'm going to close this issue due to being resovled.

![image](https://user-images.githubusercontent.com/16865714/119780365-4eeb1f80-befc-11eb-89fd-7859c7796716.png)
